dist: xenial
services:
  - xvfb
language: python
python:
  - 3.7
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - python setup.py develop
  - coverage run --source=src -m unittest discover tests -v
  - coverage report -m
  - python doctests.py
after_success:
  - coveralls
